version: '3.8'

volumes:
    mongo-db:
        driver: local
    platform-data:
        driver: local
    rabbitmq-data:
        driver: local

services:
    mongo:
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=mongoadmin
            - MONGO_INITDB_ROOT_PASSWORD=secret
        volumes:
            - mongo-db:/data/db
        ports:
            - 27020:27017

    web:
        build: ./nginx
        volumes:
            - ./nginx/templates:/etc/nginx/templates
        ports:
            - '8050:80'
        environment:
            - NGINX_HOST=localhost
            - NGINX_PORT=80
        depends_on:
            - platform

    rabbitmq:
        build: ./rabbitmq
        ports:
            - 1583:1883
            - 8583:8883
        volumes:
            - rabbitmq-data:/keys

    platform:
        image: founek2/iot-platform
        environment:
            - HOME_PAGE=http://localhost:8080
            - DATABASE_URI=mongodb://mongoadmin:secret@mongo:27017/IOTPlatform_v3?authSource=admin
            - MQTT_URL=mqtts://rabbitmq
            - MQTT_PORT=8883
            - NODE_ENV=production
            - AGENDA_JOB_TYPES=
        volumes:
            - platform-data:/keys
        depends_on:
            - mongo
