version: '3.8'

volumes:
    db:
        driver: local
    data:
        driver: local

services:
    mongo:
        build: ./mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=root
            - MONGO_INITDB_DATABASE=IOTPlatform_v3
        volumes:
            - db:/data/db
        ports:
            - 27020:27017

    web:
        build: ./nginx
        volumes:
            - ./nginx/templates:/etc/nginx/templates
        ports:
            - '8079:80'
        environment:
            - NGINX_HOST=tjv.moje
            - NGINX_PORT=80
        depends_on:
            - platform

    rabbitmq:
        build: ./rabbitmq
        ports:
            - 1889:1883

    platform:
        build: ../
        environment:
            - HOME_PAGE=http://localhost:3000
            - DATABASE_URI=mongodb://admin:admin@mongo:27017/IOTPlatform_v3
            - MQTT_URL=mqtts://rabbitmq
            - MQTT_PORT=8883
            - NODE_ENV=production
            - AGENDA_JOB_TYPES=
        volumes:
            - data:/keys
        depends_on:
            - mongo
