version: '3.8'

volumes:
    mongo-db:
        driver: local
    platform-data:
        driver: local
    rabbitmq-data:
        driver: local
    node-red-data:
        driver: local

services:
    mongo:
        image: mongo:4.4.8
        volumes:
            - mongo-db:/data/db

    nginx:
        build: ./nginx
        volumes:
            - ./nginx/templates:/etc/nginx/templates
        ports:
            - '80:80'
        environment:
            #replace
            - NGINX_HOST=example.com
        depends_on:
            - platform

    rabbitmq:
        build: ./rabbitmq
        ports:
            - 1883:1883
            - 8883:8883
        volumes:
            - rabbitmq-data:/keys

    node-red:
        build: ./node-red
        environment:
            - PLATFORM_URL=http://platform:8085
        volumes:
            - node-red-data:/node-red/data

    platform:
        image: founek2/iot-platform
        environment:
            - DATABASE_URI=mongodb://mongo:27017/IOTPlatform_v3?authSource=admin
            - MQTT_URL=mqtts://rabbitmq
            - MQTT_PORT=8883
            - NODE_ENV=production
            #replace
            - AGENDA_JOB_TYPES=
            - HOME_PAGE=http://example.com
        volumes:
            - platform-data:/keys
        depends_on:
            - mongo
