version: '3.8'

services:
    mongo:
        image: mongo:4.4.8
        restart: always
        volumes:
            - ${VOLUMES_PATH}/mongo:/data/db
        healthcheck:
            test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
            interval: 10s
            timeout: 10s
            retries: 5
            start_period: 40s

    influx-db:
        image: influxdb:2.1-alpine
        restart: always
        healthcheck:
            test:  wget --no-cache --tries=1 --spider http://localhost:8086/ping || exit 1
            interval: 30s
            timeout: 30s
            retries: 3
        environment:
            DOCKER_INFLUXDB_INIT_MODE: setup
            DOCKER_INFLUXDB_INIT_USERNAME: "${INFLUX_USERNAME}"
            DOCKER_INFLUXDB_INIT_PASSWORD: "${INFLUX_PASSWORD}"
            DOCKER_INFLUXDB_INIT_ORG: "${INFLUX_ORGANIZATION}"
            DOCKER_INFLUXDB_INIT_BUCKET: "${INFLUX_BUCKET}"
            DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: "${INFLUX_API_KEY}"
        volumes:
                - ${VOLUMES_PATH}/influx:/var/lib/influxdb2
        ports:
            - '${INFLUXDB_PORT}:8086'

    rabbitmq:
        build: ./rabbitmq
        restart: always
        healthcheck:
            test: rabbitmq-diagnostics -q ping
            interval: 30s
            timeout: 30s
            retries: 3
        ports:
            - ${MQTT_PORT}:1883
            - ${MQTTS_PORT}:8883
            - ${RABBITMQ_WEB_UI}:15672
            - ${RABBITMQ_WEB_WS}:15675
        volumes:
            - ${VOLUMES_PATH}/rabbitmq:/keys

    node-red:
        build: ./node-red
        restart: always
        ports:
            - ${NODE_RED_PORT}:1880
        environment:
            - PLATFORM_URL=http://iot-server:8085
            - TZ=Europe/Prague
        volumes:
            - ${VOLUMES_PATH}/node-red:/node-red/data

    iot-server:
        image: ${IOT_PLATFORM_IMAGE}
        restart: always
        healthcheck:
            test:  wget --no-cache --tries=1 --spider http://localhost:8085/api/main || exit 1
            interval: 30s
            retries: 3
            start_period: 20s
            timeout: 10s
        ports:
            - ${PLATFORM_PORT}:8085
        environment:
            SERVICE_AUTH_URI: http://localhost:8085
            SERVICE_MQTT_URI: http://localhost:8085
            MQTT_URL: ws://rabbitmq/ws
            MQTT_PORT: 15675
            INFLUX_URL: "http://influx-db:8086"
        volumes:
            - ${VOLUMES_PATH}/auth:/keys
        env_file: .env
        depends_on:
            - mongo
            - influx-db


